"use strict";
// var errors = {
// 	// Opsi JSHint
// 	E001: "Opsi {a} tidak valid: '{b}'.",
// 	E002: "Nilai opsi tidak valid.",
// 	// Input JSHint
// 	E003: "Diharapkan sebuah nilai JSON.",
// 	E004: "Input bukan string atau array string.",
// 	E005: "Input kosong.",
// 	E006: "Akhir program terlalu dini.",
// 	// Mode ketat (Strict mode)
// 	E007: "Pernyataan \"use strict\" hilang.",
// 	E008: "Pelanggaran strict mode.",
// 	E009: "Opsi 'validthis' tidak dapat digunakan di lingkup global.",
// 	E010: "'with' tidak diizinkan dalam strict mode.",
// 	// Konstanta
// 	E011: "'{a}' sudah pernah dideklarasikan.",
// 	E012: "Inisialisasi untuk konstanta '{a}' hilang.",
// 	E013: "Mencoba menimpa '{a}' yang merupakan konstanta.",
// 	// Ekspresi reguler
// 	E014: "Literal ekspresi reguler dapat membingungkan dengan '/='.",
// 	E015: "Ekspresi reguler tidak tertutup.",
// 	E016: "Ekspresi reguler tidak valid.",
// 	// Token
// 	E017: "Komentar tidak tertutup.",
// 	E018: "Komentar belum dimulai.",
// 	E019: "'{a}' tidak memiliki pasangan.",
// 	E020: "Diharapkan '{a}' untuk berpasangan dengan '{b}' dari baris {c} namun ditemukan '{d}'.",
// 	E021: "Diharapkan '{a}' namun ditemukan '{b}'.",
// 	E022: "Kesalahan pemutusan baris '{a}'.",
// 	E023: "Kehilangan '{a}'.",
// 	E024: "Tidak terduga '{a}'.",
// 	E025: "Kehilangan ':' pada klausa case.",
// 	E026: "Kehilangan '}' untuk pasangan '{' dari baris {a}.",
// 	E027: "Kehilangan ']' untuk pasangan '[' dari baris {a}.",
// 	E028: "Koma ilegal.",
// 	E029: "String tidak tertutup.",
// 	// Lain-lain
// 	E030: "Diharapkan sebuah identifier namun ditemukan '{a}'.",
// 	E031: "Penugasan (assignment) tidak valid.",
// 	E032: "Diharapkan bilangan bulat kecil atau 'false' namun ditemukan '{a}'.",
// 	E033: "Diharapkan sebuah operator namun ditemukan '{a}'.",
// 	E034: "get/set adalah fitur ES5.",
// 	E035: "Nama properti hilang.",
// 	E036: "Diharapkan sebuah pernyataan namun ditemukan sebuah blok.",
// 	E037: null,
// 	E038: null,
// 	E039: "Deklarasi fungsi tidak dapat dipanggil. Bungkus seluruh pemanggilan fungsi dalam tanda kurung.",
// 	E040: "Setiap nilai harus memiliki label case sendiri.",
// 	E041: "Kesalahan sintaks yang tidak dapat dipulihkan.",
// 	E042: "Berhenti.",
// 	E043: "Terlalu banyak kesalahan.",
// 	E044: null,
// 	E045: "Loop for each tidak valid.",
// 	E046: "Ekspresi yield hanya boleh muncul di dalam fungsi generator.",
// 	E047: null,
// 	E048: "Deklarasi {a} tidak langsung berada di dalam blok.",
// 	E049: "Sebuah {a} tidak boleh diberi nama '{b}'.",
// 	E050: "Mozilla mengharuskan ekspresi yield diberi tanda kurung di sini.",
// 	E051: null,
// 	E052: "Template literal tidak tertutup.",
// 	E053: "Deklarasi {a} hanya diizinkan di tingkat atas lingkup modul.",
// 	E054: "Properti kelas harus berupa metode. Diharapkan '(' namun ditemukan '{a}'.",
// 	E055: "Opsi '{a}' tidak dapat diatur setelah ada kode yang dapat dieksekusi.",
// 	E056: "'{a}' digunakan sebelum dideklarasikan, yang ilegal untuk variabel '{b}'.",
// 	E057: "Meta property tidak valid: '{a}.{b}'.",
// 	E058: "Titik koma hilang.",
// 	E059: "Nilai tidak kompatibel untuk opsi linting '{a}' dan '{b}'.",
// 	E060: "Nilai yang tidak dapat dipanggil tidak dapat digunakan sebagai operand kedua untuk instanceof.",
// 	E061: "Posisi ekspresi 'yield' tidak valid (pertimbangkan untuk membungkusnya dalam tanda kurung).",
// 	E062: "Parameter rest tidak mendukung nilai default.",
// 	E063: "Properti super hanya boleh digunakan di dalam tubuh metode.",
// 	E064: "Pemanggilan super hanya boleh digunakan di dalam tubuh metode kelas.",
// 	E065: "Fungsi yang didefinisikan di luar strict mode dengan daftar parameter non-sederhana tidak boleh mengaktifkan strict mode.",
// 	E066: "Iterasi asinkron hanya tersedia dengan loop for-of.",
// 	E067: "Literal numerik salah format: '{a}'.",
// 	E068: "Desimal dengan nol di depan tidak diizinkan dalam strict mode.",
// 	E069: "Binding ekspor duplikat: '{a}'.",
// 	E070: "import.meta hanya boleh digunakan dalam kode modul."
// };
// var warnings = {
// 	W001: "'hasOwnProperty' adalah nama yang kurang tepat.",
// 	W002: "Nilai dari '{a}' mungkin akan ditimpa di IE 8 dan versi sebelumnya.",
// 	W003: "'{a}' digunakan sebelum didefinisikan.",
// 	W004: "'{a}' sudah didefinisikan.",
// 	W005: "Titik setelah angka dapat membingungkan dengan tanda desimal.",
// 	W006: "Tanda minus yang membingungkan.",
// 	W007: "Tanda plus yang membingungkan.",
// 	W008: "Titik desimal di awal dapat membingungkan dengan tanda titik: '{a}'.",
// 	W009: "Notasi literal array [] lebih disarankan.",
// 	W010: "Notasi literal objek {} lebih disarankan.",
// 	W014: "Pemutusan baris sebelum '{a}' dapat menyesatkan; pembaca mungkin menganggap ini sebagai batas ekspresi.",
// 	W016: "Penggunaan '{a}' yang tidak terduga.",
// 	W017: "Operand kurang tepat.",
// 	W018: "Penggunaan '{a}' yang membingungkan.",
// 	W019: "Gunakan fungsi isNaN untuk membandingkan dengan NaN.",
// 	W020: "Hanya-baca.",
// 	W021: "Penugasan ulang '{a}', yang merupakan {b}. Gunakan 'var' atau 'let' untuk mendeklarasikan binding yang dapat berubah.",
// 	W022: "Jangan menetapkan nilai pada parameter pengecualian.",
// 	W024: "Diharapkan sebuah identifier tetapi malah menemukan '{a}' (kata yang dicadangkan).",
// 	W025: "Nama hilang pada deklarasi fungsi.",
// 	W026: "Fungsi di dalam sebaiknya ditempatkan di bagian atas fungsi luar.",
// 	W027: "'{a}' tidak dapat dijangkau setelah '{b}'.",
// 	W028: "Label '{a}' pada pernyataan {b}.",
// 	W030: "Diharapkan penugasan atau pemanggilan fungsi tetapi malah menemukan ekspresi.",
// 	W031: "Jangan gunakan 'new' untuk efek samping.",
// 	W032: "Titik koma yang tidak perlu.",
// 	W033: "Titik koma hilang.",
// 	W034: "Direktif \"{a}\" yang tidak perlu.",
// 	W035: "Blok kosong.",
// 	W036: "/*member '{a}' yang tidak terduga.",
// 	W037: "'{a}' adalah label pernyataan.",
// 	W038: "'{a}' digunakan di luar cakupan.",
// 	W040: "Jika fungsi mode ketat dijalankan menggunakan pemanggilan fungsi, nilai 'this'-nya akan menjadi undefined.",
// 	W042: "Hindari pelolosan EOL.",
// 	W043: "Pelolosan EOL yang kurang tepat. Gunakan opsi multistr jika diperlukan.",
// 	W044: "Pelolosan yang tidak perlu atau kurang tepat.",
// 	W045: "Nilai yang dijelaskan oleh literal numerik tidak dapat direpresentasikan secara akurat dengan nilai number: '{a}'.",
// 	W046: "Jangan gunakan nol tambahan di depan '{a}'.",
// 	W047: "Titik desimal di akhir dapat membingungkan dengan tanda titik: '{a}'.",
// 	W048: "Karakter kontrol yang tidak terduga dalam ekspresi reguler.",
// 	W049: "Karakter yang diloloskan '{a}' tidak terduga dalam ekspresi reguler.",
// 	W050: "URL JavaScript.",
// 	W051: "Variabel tidak boleh dihapus.",
// 	W052: "'{a}' yang tidak terduga.",
// 	W053: "Jangan gunakan {a} sebagai konstruktor.",
// 	W054: "Konstruktor Function adalah bentuk dari eval.",
// 	W055: "Nama konstruktor sebaiknya diawali dengan huruf kapital.",
// 	W056: "Konstruktor kurang tepat.",
// 	W057: "Konstruksi tidak biasa. Apakah 'new' diperlukan?",
// 	W058: "Hilang '()' saat memanggil konstruktor.",
// 	W059: "Hindari arguments.{a}.",
// 	W060: "document.write dapat menjadi bentuk eval.",
// 	W061: "eval dapat berisiko.",
// 	W062: "Bungkus pemanggilan fungsi langsung dalam tanda kurung untuk membantu pembaca memahami bahwa ekspresi tersebut adalah hasil dari fungsi, bukan fungsi itu sendiri.",
// 	W063: "Math bukan sebuah fungsi.",
// 	W064: "Hilang awalan 'new' saat memanggil konstruktor.",
// 	W065: "Parameter radix hilang.",
// 	W066: "Eval implisit. Pertimbangkan untuk mengoper fungsi daripada string.",
// 	W067: "Pemanggilan fungsi yang tidak lazim.",
// 	W068: "Membungkus literal fungsi non-IIFE dalam tanda kurung tidak perlu.",
// 	W069: "['{a}'] lebih baik ditulis dalam notasi titik.",
// 	W070: "Koma tambahan. (merusak versi IE lama)",
// 	W071: "Fungsi ini memiliki terlalu banyak pernyataan. ({a})",
// 	W072: "Fungsi ini memiliki terlalu banyak parameter. ({a})",
// 	W073: "Blok bersarang terlalu dalam. ({a})",
// 	W074: "Kompleksitas siklomatis fungsi ini terlalu tinggi. ({a})",
// 	W075: "Duplikasi {a} '{b}'.",
// 	W076: "Parameter '{a}' tidak terduga dalam fungsi get {b}.",
// 	W077: "Diharapkan satu parameter tunggal dalam fungsi set {a}.",
// 	W078: "Setter didefinisikan tanpa getter.",
// 	W079: "Pendefinisian ulang '{a}'.",
// 	W080: "Tidak perlu menginisialisasi '{a}' ke 'undefined'.",
// 	W082: "Deklarasi fungsi tidak boleh ditempatkan di dalam blok. Gunakan ekspresi fungsi atau pindahkan ke bagian atas fungsi luar.",
// 	W083: "Fungsi yang dideklarasikan di dalam loop yang mereferensikan variabel luar dapat menyebabkan semantik yang membingungkan. ({a})",
// 	W084: "Diharapkan ekspresi kondisional tetapi malah menemukan penugasan.",
// 	W085: "Jangan gunakan 'with'.",
// 	W086: "Diharapkan pernyataan 'break' sebelum '{a}'.",
// 	W087: "Pernyataan 'debugger' terlupakan?",
// 	W088: "Membuat variabel 'for' global. Harusnya 'for (var {a} ...'.",
// 	W089: "Badan dari for in harus dibungkus dalam pernyataan if untuk memfilter properti yang tidak diinginkan dari prototype.",
// 	W090: "'{a}' bukan label pernyataan.",
// 	W093: "Apakah maksud Anda mengembalikan kondisi alih-alih penugasan?",
// 	W094: "Koma tidak terduga.",
// 	W095: "Diharapkan string tetapi malah menemukan {a}.",
// 	W096: "Kunci '{a}' dapat menghasilkan hasil yang tidak terduga.",
// 	W097: "Gunakan bentuk fungsi dari \"use strict\".",
// 	W098: "'{a}' didefinisikan tetapi tidak pernah digunakan.",
// 	W101: "Baris terlalu panjang.",
// 	W103: "Properti '{a}' sudah usang.",
// 	W104: "'{a}' tersedia di ES{b} (gunakan 'esversion: {b}') atau ekstensi JS Mozilla (gunakan moz).",
// 	W106: "Identifier '{a}' tidak dalam format camel case.",
// 	W107: "URL skrip.",
// 	W108: "String harus menggunakan tanda kutip ganda.",
// 	W109: "String harus menggunakan tanda kutip tunggal.",
// 	W110: "Campuran tanda kutip ganda dan tunggal.",
// 	W112: "String tidak tertutup.",
// 	W113: "Karakter kontrol dalam string: {a}.",
// 	W114: "Hindari {a}.",
// 	W115: "Literal oktal tidak diizinkan dalam mode ketat.",
// 	W116: "Diharapkan '{a}' tetapi malah menemukan '{b}'.",
// 	W117: "'{a}' tidak didefinisikan.",
// 	W118: "'{a}' hanya tersedia di ekstensi JavaScript Mozilla (gunakan opsi moz).",
// 	W119: "'{a}' hanya tersedia di ES{b} (gunakan 'esversion: {b}')."
// };
// info info = {
// 	I001: "Peringatan koma dapat dimatikan dengan 'laxcomma'.",
// 	I003: "Opsi ES5 sekarang diatur secara default."
// };
